version: '3.4'
services:
  web:
    image: $REPOSITORY/ade_web:$TAG
    ports:
      - "$PORT:5000"
    volumes:
      - conf2:/frontend/conf/
    environment:
      - "SSL=$SSL"
  backend:
    image: "$REPOSITORY/ade_backend:$TAG"
    ports:
      - "8787:8787"
    volumes:
      - conf2:/backend/conf/
  elasticsearch:
    image: $REPOSITORY/elasticsearch:7.2.1
    volumes:
      - data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node

volumes:
  conf2:
  data:
